# config.yaml

tickers:
  - MRNY
  - TSLY
  - YETH
  - QQQY
  - FIAT
  - YMAG
  - YMAX
  - LFGY
  - GPTY
  - WDTE
  - JEPI
  - JEPQ

polygon_api_key: "oO15tiw11M"

yahoo_fallback: true  # Use Yahoo Finance scraping if NAV missing

email_settings:
  smtp_server: "smtp.gmail.com"
  smtp_port: 587
  sender_email: "chris@cmcsec.com"
  sender_password: ""
  receivers:
    - "chris@cmcsec.com"
    - "number@txt.att.net"   # AT&T SMS Gateway

risk_thresholds:
  nav_decay_pct: 0.05         # 5% NAV drop triggers alert
  premium_discount_pct: 0.02  # 2% deviation triggers alert
  volume_drop_pct: 0.30       # 30% volume drop triggers alert
  dividend_cut_pct: 0.20      # 20% dividend cut triggers alert
  aum_floor_million: 50       # Manual check: alert if AUM falls below $50M

